# This playbook installs and configures some of the common packages in the
# development VM.

- hosts: all
  sudo: yes
  tasks:
  - name: install git
    apt: name=git state=present update_cache=yes

  - name: install ruby2.0
    apt: name=ruby2.0 state=present

  - name: install ruby2.0-dev
    apt: name=ruby2.0-dev state=present

  - name: install python-pip
    apt: name=python-pip state=present

  - name: install python-dev
    apt: name=python-dev state=present

  - name: install tig
    apt: name=tig state=present

  - name: install htop
    apt: name=htop state=present

  - name: install firefox
    apt: name=firefox state=present

  - name: install ansible 1.5.3
    apt: name=ansible state=present

  - name: install fig
    pip: name=fig

  - name: install cowsay
    apt: name=cowsay state=present
