# This playbook installs and configures various javascript
# related software and its development environment

- hosts: all
  sudo: yes
  tasks:
  - name: install nodejs
    apt: name=nodejs state=present

  - name: symlink of node to nodejs
    command: ln -s /usr/bin/nodejs /usr/bin/node
    ignore_errors: True

  - name: install npm
    apt: name=npm state=present

  - name: install the awesome API renderer
    npm: name=aglio global=yes

  - name: install bower
    npm: name=bower global=yes

  - name: install grunt-cli
    npm: name=grunt-cli global=yes

  - name: install yo
    npm: name=yo global=yes

  - name: install meanjs generator
    npm: name=generator-meanjs global=yes

  - name: install tern
    npm: name=tern global=yes
